name: Hello World

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # Grants write access to pull requests

jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

  main:
    needs: startup
    runs-on: ubuntu-latest  # Adding runs-on to specify the environment
    steps:
      - name: comment on PR
      - run: echo "hello world"
      - run: gh pr comment $PR_URL --body "Thanks for the pr. We will review it shortly."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: checkout code
        uses: actions/checkout@2
        with: 
          fetch-depth: 0
      - name: check for buttons
      - run: ./.github/scripts/checker.sh
      - env:
          FILE: ./src/components/Buttons.js
